//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int IDSettings { get; set; }
        public int RowHall { get; set; }
        public int PlaceHall { get; set; }
        public string HiddenPlaces { get; set; }
        public System.DateTime DateTimeChange { get; set; }
    }
}
