//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int IDTicket { get; set; }
        public int IDSession { get; set; }
        public int RowNumber { get; set; }
        public int PlaceNumber { get; set; }
        public int IDEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Session Session { get; set; }
    }
}
