//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorsInMovies
    {
        public int IDActorsInMovies { get; set; }
        public int IDMovie { get; set; }
        public int IDActor { get; set; }
        public string Character { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
